---
params: 
    title: ""
title: "`r params$title`"
author: ""
output: teproj::word_document_te
---

```{r setup, include = FALSE}
# rmarkdown::render(file.path("R", "01-main.Rmd"))
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(
  echo = TRUE,
  cache = FALSE,
  include = TRUE,
  fig.align = "center",
  fig.width = 6,
  fig.height = 6,
  # out.width = 6,
  # out.height = 6,
  warning = FALSE,
  message = FALSE
)
```

```{r config, include = FALSE}
library("tidyverse")

config <-
  list(
    path_data = file.path("data", "data.csv")
  )
```

```{r approach1_diagram_new1, fig.cap = "capton"}
DiagrammeR::grViz("
digraph {

  graph [overlap = true, fontsize = 24]

  node [shape = box,
        fontname = Arial]
  a [label = '@@1']
  b [label = '@@2']
  c [label = '@@3']

  c->a
  b->a
}

[1]: stringr::str_wrap('\"`sprintf()`\" function with method as the primary input, binding the lists returned from the base and method-specific functions and calling caret::train()', 60)
[2]: stringr::str_wrap('base {caret} function, defining constants across all methods and method-specific parameters to be evaluated', 60)
[3]: stringr::str_wrap('Method-specific function, with tuneGrid and other method-specific parameters defined', 60)
")
```

```{r approach1_diagram_new2, fig.cap = "capton", include = FALSE, eval = FALSE}
DiagrammeR::grViz("
digraph {

  graph [overlap = true, fontsize = 10]

  node [shape = box,
        fontname = Arial]
  a [label = '@@1']
  b [label = '@@2']
  c [label = '@@3']

  c->a
  b->a
}

[1]: stringr::str_wrap('sprintf function with `method` as the primary input, binding the lists returned from the base and method-specific functions and calling `caret::train()`', 60)
[2]: stringr::str_wrap('base `{caret}` function, defining constants across all methods and method-specific parameters to be evaluated', 60)
[3]: stringr::str_wrap('Method-specific function, with `tuneGrid` and other method-specific parameters defined', 60)
")
```

```{r approach1_diagram, fig.cap = "capton", include = FALSE, eval = FALSE}
DiagrammeR::grViz("
digraph {

  graph [overlap = true, fontsize = 10]

  node [shape = box,
        fontname = Arial]
  a [label = '@@1']
  b [label = '@@2']
  c [label = '@@3']

  c->a
  b->a
}

[1]: stringr::str_wrap('\"sprintf\" function with `method` as the primary input, binding the lists returned from the \"base\" and \"method-specific\" functions and calling `caret::train()`', 60)
[2]: stringr::str_wrap('\"base\" `{caret}` function, defining \"constants\" across all methods and method-specific parameters to be evaluated', 60)
[3]: stringr::str_wrap('\"Method-specific\" function, with `tuneGrid` and other method-specific parameters defined', 60)
")
```
